[2024-05-21 15:32:07,502: INFO: main]: Welcome to our custom log
[2024-05-21 15:41:26,371: INFO: main]: Welcome to our custom log
[2024-05-22 21:34:03,798:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-22 21:34:03,800:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-22 22:16:01,963:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:16:01,966:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-22 22:16:35,258:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:16:35,261:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-22 22:16:35,262:INFO:common:created directory at: artifacts]
[2024-05-22 22:19:51,857:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:19:51,860:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-22 22:19:51,862:INFO:common:created directory at: artifacts]
[2024-05-22 22:19:51,864:INFO:common:created directory at: artifacts/data_ingestion]
[2024-05-22 22:19:51,866:INFO:906975951:Downloading data from https://drive.google.com/file/d/1mRWHy3j2a29NnCuA93q1i5lU2Dl_fYu8/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 22:20:42,123:INFO:906975951:Download data from https://drive.google.com/file/d/1mRWHy3j2a29NnCuA93q1i5lU2Dl_fYu8/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 22:33:40,314:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:33:40,317:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-22 22:33:40,319:INFO:common:created directory at: artifacts]
[2024-05-22 22:33:40,321:INFO:common:created directory at: artifacts/data_ingestion]
[2024-05-22 22:33:40,323:INFO:906975951:Downloading data from https://drive.google.com/file/d/1-YuxGUpXRE68pyo1VETd9w6Yyh7yoC4T/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 22:34:42,230:INFO:906975951:Download data from https://drive.google.com/file/d/1-YuxGUpXRE68pyo1VETd9w6Yyh7yoC4T/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 22:46:35,171:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-22 22:46:35,174:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-22 22:46:35,176:INFO:common:created directory at: artifacts]
[2024-05-22 22:46:35,178:INFO:common:created directory at: artifacts/data_ingestion]
[2024-05-22 22:46:35,180:INFO:906975951:Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-22 22:47:23,453:INFO:906975951:Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-23 20:02:48,708: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<<
[2024-05-23 20:02:48,710: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-23 20:02:48,711: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-23 20:02:48,712: INFO: common]: created directory at: artifacts
[2024-05-23 20:02:48,712: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-23 20:02:48,713: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-23 20:03:40,582: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-23 20:03:41,903: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<<

x============x
[2024-05-25 00:21:06,448:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:21:06,454:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:21:06,457:INFO:common:created directory at: artifacts]
[2024-05-25 00:21:06,460:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 00:37:53,913: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-25 00:37:56,404: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<<
[2024-05-25 00:37:56,406: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-25 00:37:56,407: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-25 00:37:56,408: INFO: common]: created directory at: artifacts
[2024-05-25 00:37:56,409: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-25 00:37:56,409: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-25 00:38:45,823: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-25 00:38:47,141: INFO: main]: >>>>>> stage Data Ingestion stage completed  <<<<<<<

x============x
[2024-05-25 00:38:47,142: INFO: main]: >>>>>> stage Prepare Base Model started <<<<<<<
[2024-05-25 00:38:47,148: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-25 00:38:47,150: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-25 00:38:47,151: INFO: common]: created directory at: artifacts
[2024-05-25 00:38:47,152: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-25 00:41:11,762: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-25 00:41:12,476: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<<
[2024-05-25 00:41:12,479: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-25 00:41:12,483: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-25 00:41:12,483: INFO: common]: created directory at: artifacts
[2024-05-25 00:41:12,483: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-25 00:41:12,484: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-25 00:42:01,886: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-25 00:42:02,713: INFO: main]: >>>>>> stage Data Ingestion stage completed  <<<<<<<

x============x
[2024-05-25 00:42:02,714: INFO: main]: >>>>>> stage Prepare Base Model started <<<<<<<
[2024-05-25 00:42:02,715: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-25 00:42:02,717: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-25 00:42:02,718: INFO: common]: created directory at: artifacts
[2024-05-25 00:42:02,718: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-25 00:44:46,968:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:44:46,972:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:44:46,974:INFO:common:created directory at: artifacts]
[2024-05-25 00:44:46,976:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 00:45:23,201:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:45:23,205:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:45:23,209:INFO:common:created directory at: artifacts]
[2024-05-25 00:45:23,210:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 00:47:56,492:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:47:56,496:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:47:56,498:INFO:common:created directory at: artifacts]
[2024-05-25 00:51:39,390:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:51:39,395:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:51:39,398:INFO:common:created directory at: artifacts]
[2024-05-25 00:53:32,734:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:53:32,739:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:53:32,742:INFO:common:created directory at: artifacts]
[2024-05-25 00:53:38,833:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:53:38,839:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:53:38,842:INFO:common:created directory at: artifacts]
[2024-05-25 00:54:20,128:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:54:20,133:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:54:20,136:INFO:common:created directory at: artifacts]
[2024-05-25 00:54:26,202:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:54:26,206:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:54:26,208:INFO:common:created directory at: artifacts]
[2024-05-25 00:54:37,752:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:54:37,758:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:54:37,761:INFO:common:created directory at: artifacts]
[2024-05-25 00:54:56,698:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:54:56,702:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:54:56,705:INFO:common:created directory at: artifacts]
[2024-05-25 00:54:56,706:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 00:55:57,462:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:55:57,468:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:55:57,470:INFO:common:created directory at: artifacts]
[2024-05-25 00:55:57,472:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 00:56:06,938:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:56:06,943:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:56:06,945:INFO:common:created directory at: artifacts]
[2024-05-25 00:56:06,947:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 00:58:02,459:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:58:02,462:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:58:02,464:INFO:common:created directory at: artifacts]
[2024-05-25 00:58:02,536:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:58:02,540:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:58:02,543:INFO:common:created directory at: artifacts]
[2024-05-25 00:58:02,545:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 00:59:43,783:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 00:59:43,788:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 00:59:43,791:INFO:common:created directory at: artifacts]
[2024-05-25 01:00:16,527:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 01:00:16,530:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 01:00:16,533:INFO:common:created directory at: artifacts]
[2024-05-25 01:00:21,686:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 01:00:21,690:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 01:00:21,692:INFO:common:created directory at: artifacts]
[2024-05-25 01:00:21,695:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 01:00:53,601:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 01:00:53,606:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 01:00:53,608:INFO:common:created directory at: artifacts]
[2024-05-25 01:00:53,611:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 01:02:47,255:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 01:02:47,260:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 01:02:47,262:INFO:common:created directory at: artifacts]
[2024-05-25 01:02:54,344:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 01:02:54,349:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-25 01:02:54,351:INFO:common:created directory at: artifacts]
[2024-05-25 01:02:54,353:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 01:04:33,984:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 01:04:33,987:INFO:common:yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully]
[2024-05-25 01:04:33,990:INFO:common:created directory at: artifacts]
[2024-05-25 01:04:34,061:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 01:04:34,065:INFO:common:yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully]
[2024-05-25 01:04:34,068:INFO:common:created directory at: artifacts]
[2024-05-25 01:04:34,120:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 01:04:34,125:INFO:common:yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully]
[2024-05-25 01:04:34,127:INFO:common:created directory at: artifacts]
[2024-05-25 01:04:34,129:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 01:05:36,148:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 01:05:36,152:INFO:common:yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully]
[2024-05-25 01:05:36,155:INFO:common:created directory at: artifacts]
[2024-05-25 01:05:36,280:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 01:05:36,285:INFO:common:yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully]
[2024-05-25 01:05:36,288:INFO:common:created directory at: artifacts]
[2024-05-25 01:05:36,339:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 01:05:36,343:INFO:common:yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully]
[2024-05-25 01:05:36,346:INFO:common:created directory at: artifacts]
[2024-05-25 01:05:36,348:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 01:06:10,589:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-25 01:11:06,876:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-25 01:11:06,881:INFO:common:yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully]
[2024-05-25 01:11:06,883:INFO:common:created directory at: artifacts]
[2024-05-25 01:11:06,885:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-05-25 01:11:07,722:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-25 01:12:23,745: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-25 01:12:24,467: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<<
[2024-05-25 01:12:24,469: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-25 01:12:24,470: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-25 01:12:24,470: INFO: common]: created directory at: artifacts
[2024-05-25 01:12:24,472: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-25 01:12:24,472: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-25 01:13:17,940: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-25 01:13:18,905: INFO: main]: >>>>>> stage Data Ingestion stage completed  <<<<<<<

x============x
[2024-05-25 01:13:18,906: INFO: main]: >>>>>> stage Prepare Base Model started <<<<<<<
[2024-05-25 01:13:18,907: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-25 01:13:18,909: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-25 01:13:18,909: INFO: common]: created directory at: artifacts
[2024-05-25 01:13:18,910: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-25 01:13:19,615: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-25 01:13:19,858: INFO: main]: >>>>>> stage Prepare Base Model completed <<<<<<<

x============x
[2024-05-26 21:12:54,203: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 21:12:54,208: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-26 21:12:54,211: INFO: common]: created directory at: artifacts
[2024-05-26 21:12:54,213: INFO: common]: created directory at: artifacts\training
[2024-05-26 21:13:51,083: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 21:13:51,089: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-26 21:13:51,091: INFO: common]: created directory at: artifacts
[2024-05-26 21:13:51,094: INFO: common]: created directory at: artifacts\training
[2024-05-26 21:14:18,240: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 21:14:18,245: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-26 21:14:18,247: INFO: common]: created directory at: artifacts
[2024-05-26 21:14:18,249: INFO: common]: created directory at: artifacts\training
[2024-05-26 21:28:20,411: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-26 21:28:22,995: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-26 21:28:22,998: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 21:28:23,002: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-26 21:28:23,003: INFO: common]: created directory at: artifacts
[2024-05-26 21:28:23,004: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-26 21:28:23,006: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-26 21:29:15,204: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-26 21:29:16,380: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-26 21:29:16,380: INFO: main]: *******************
[2024-05-26 21:29:16,381: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-26 21:29:16,383: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 21:29:16,384: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-26 21:29:16,385: INFO: common]: created directory at: artifacts
[2024-05-26 21:29:16,386: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-26 21:29:17,191: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-26 21:29:17,430: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-26 21:29:17,431: INFO: main]: ************************************************
[2024-05-26 21:29:17,431: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-26 21:29:17,433: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 21:29:17,435: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-26 21:29:17,436: INFO: common]: created directory at: artifacts
[2024-05-26 21:29:17,437: INFO: common]: created directory at: artifacts\training
[2024-05-26 21:30:29,281: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-26 23:02:04,630: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 23:02:04,634: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-26 23:02:04,637: INFO: common]: created directory at: artifacts
[2024-05-26 23:03:25,945: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-26 23:03:25,948: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-26 23:03:26,028: WARNING: connectionpool]: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /mcmlxiv/Kidney-Disease-Classification.mlflow/api/2.0/mlflow/runs/create
[2024-05-26 23:03:28,616: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 23:03:28,621: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-26 23:03:28,624: INFO: common]: created directory at: artifacts
[2024-05-26 23:08:21,574: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-26 23:08:21,578: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-26 23:08:23,718: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 23:08:23,723: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-26 23:08:23,726: INFO: common]: created directory at: artifacts
[2024-05-26 23:09:44,335: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-26 23:09:44,339: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-26 23:09:46,543: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 23:09:46,547: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-26 23:09:46,549: INFO: common]: created directory at: artifacts
[2024-05-26 23:09:57,168: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-26 23:09:57,171: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-26 23:09:59,197: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 23:09:59,202: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-26 23:09:59,204: INFO: common]: created directory at: artifacts
[2024-05-26 23:11:32,721: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-26 23:11:32,724: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-26 23:11:34,810: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 23:11:34,814: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-26 23:11:34,816: INFO: common]: created directory at: artifacts
[2024-05-26 23:11:52,251: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-26 23:11:52,254: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-26 23:11:54,348: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 23:11:54,352: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-26 23:11:54,354: INFO: common]: created directory at: artifacts
[2024-05-26 23:12:28,019: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-26 23:12:28,023: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-26 23:12:30,108: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 23:12:30,111: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-26 23:12:30,114: INFO: common]: created directory at: artifacts
[2024-05-26 23:13:04,837: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-26 23:13:04,842: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-26 23:13:06,998: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 23:13:07,002: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-26 23:13:07,005: INFO: common]: created directory at: artifacts
[2024-05-26 23:13:22,658: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-26 23:13:22,662: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-26 23:13:24,697: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 23:13:24,701: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-26 23:13:24,703: INFO: common]: created directory at: artifacts
[2024-05-26 23:13:54,290: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-26 23:13:54,294: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-26 23:13:56,424: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 23:13:56,429: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-26 23:13:56,431: INFO: common]: created directory at: artifacts
[2024-05-26 23:15:12,448: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-26 23:15:12,451: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-26 23:15:14,449: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-26 23:15:14,452: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-26 23:15:14,455: INFO: common]: created directory at: artifacts
[2024-05-26 23:15:40,365: INFO: common]: json files saved at: scores.json
[2024-05-26 23:15:43,008: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-26 23:15:44,224: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmp91gl32pd\model\data\model\assets
[2024-05-27 16:13:42,808: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 16:13:42,812: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-27 16:13:42,814: INFO: common]: created directory at: artifacts
[2024-05-27 16:14:07,509: INFO: common]: json files saved at: scores.json
[2024-05-27 16:14:10,299: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-27 16:14:11,237: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmp6pkjrnm7\model\data\model\assets
[2024-05-27 16:15:30,647: WARNING: connectionpool]: Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /mcmlxiv/Kidney-Disease-Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/f5b905e747374fde889a4a3dc7b8ed42/9791f8bfe1054a569328b9225fe46963/artifacts/model/data/model/variables/variables.data-00000-of-00001
[2024-05-27 16:35:53,981: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 16:35:58,613: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 16:35:58,616: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 16:35:58,618: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 16:35:58,618: INFO: common]: created directory at: artifacts
[2024-05-27 16:35:58,619: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 16:35:58,620: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 16:36:00,054: ERROR: main]: HTTPSConnectionPool(host='doc-0s-bg-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/v8kui4o7n0q0cqdum1crulfg9td9a8b3/1716798900000/13776470301398363934/*/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY?uuid=0cf9d249-5609-486d-b1aa-4798559fdf6c (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D6721D7A50>: Failed to resolve 'doc-0s-bg-docs.googleusercontent.com' ([Errno 11001] getaddrinfo failed)"))
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 492, in _make_request
    raise new_e
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001D6721D7A50>: Failed to resolve 'doc-0s-bg-docs.googleusercontent.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='doc-0s-bg-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/v8kui4o7n0q0cqdum1crulfg9td9a8b3/1716798900000/13776470301398363934/*/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY?uuid=0cf9d249-5609-486d-b1aa-4798559fdf6c (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D6721D7A50>: Failed to resolve 'doc-0s-bg-docs.googleusercontent.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ML projects\ML class\Kidney-Disease-Classification\main.py", line 11, in <module>
    data_ingestion.main()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix + file_id, zip_download_dir)
  File "C:\Users\User\anaconda3\Lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
           ^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='doc-0s-bg-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/v8kui4o7n0q0cqdum1crulfg9td9a8b3/1716798900000/13776470301398363934/*/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY?uuid=0cf9d249-5609-486d-b1aa-4798559fdf6c (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D6721D7A50>: Failed to resolve 'doc-0s-bg-docs.googleusercontent.com' ([Errno 11001] getaddrinfo failed)"))
[2024-05-27 16:42:16,465:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-27 16:42:16,470:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-27 16:42:16,473:INFO:common:created directory at: artifacts]
[2024-05-27 16:42:16,475:INFO:common:created directory at: artifacts/data_ingestion]
[2024-05-27 16:42:16,477:INFO:906975951:Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-27 16:44:30,114:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-27 16:44:30,119:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-27 16:44:30,122:INFO:common:created directory at: artifacts]
[2024-05-27 16:44:30,124:INFO:common:created directory at: artifacts/data_ingestion]
[2024-05-27 16:44:30,126:INFO:906975951:Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-27 16:45:29,911:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-05-27 16:45:29,914:INFO:common:yaml file: params.yaml loaded successfully]
[2024-05-27 16:45:29,917:INFO:common:created directory at: artifacts]
[2024-05-27 16:45:29,920:INFO:common:created directory at: artifacts/data_ingestion]
[2024-05-27 16:45:29,922:INFO:906975951:Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-27 16:46:18,754:INFO:906975951:Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-27 16:47:38,220: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 16:47:41,877: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 16:47:41,879: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 16:47:41,881: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 16:47:41,881: INFO: common]: created directory at: artifacts
[2024-05-27 16:47:41,882: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 16:47:41,882: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 16:48:31,367: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 16:48:32,208: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 16:48:32,209: INFO: main]: *******************
[2024-05-27 16:48:32,214: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 16:48:32,216: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 16:48:32,219: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 16:48:32,220: INFO: common]: created directory at: artifacts
[2024-05-27 16:48:32,221: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 16:48:32,891: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 16:48:33,123: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 16:48:33,123: INFO: main]: ************************************************
[2024-05-27 16:48:33,124: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 16:48:33,126: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 16:48:33,127: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 16:48:33,128: INFO: common]: created directory at: artifacts
[2024-05-27 16:48:33,129: INFO: common]: created directory at: artifacts\training
[2024-05-27 16:49:41,731: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 16:49:41,732: INFO: main]: ***********************************************
[2024-05-27 16:49:41,732: INFO: main]: >>>>>> stage Evaluation started <<<<<<<
[2024-05-27 16:49:41,736: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 16:49:41,739: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 16:49:41,740: INFO: common]: created directory at: artifacts
[2024-05-27 16:50:05,084: INFO: common]: json files saved at: scores.json
[2024-05-27 16:50:07,732: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-27 16:50:09,303: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmprbraz243\model\data\model\assets
[2024-05-27 16:50:26,331: INFO: dir_util]: creating D:\ML projects\ML class\Kidney-Disease-Classification\mlruns\0\e4a1ff82646545e68bbcbcd98a25a2df\artifacts\model\data
[2024-05-27 16:50:26,333: INFO: dir_util]: creating D:\ML projects\ML class\Kidney-Disease-Classification\mlruns\0\e4a1ff82646545e68bbcbcd98a25a2df\artifacts\model\data\model
[2024-05-27 16:50:26,334: INFO: dir_util]: creating D:\ML projects\ML class\Kidney-Disease-Classification\mlruns\0\e4a1ff82646545e68bbcbcd98a25a2df\artifacts\model\data\model\assets
[2024-05-27 16:50:26,339: INFO: dir_util]: creating D:\ML projects\ML class\Kidney-Disease-Classification\mlruns\0\e4a1ff82646545e68bbcbcd98a25a2df\artifacts\model\data\model\variables
[2024-05-27 16:50:26,464: INFO: main]: >>>>>> stage Evaluation completed <<<<<<<

x============x
[2024-05-27 16:52:13,121: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 16:52:16,612: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 16:52:16,615: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 16:52:16,617: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 16:52:16,618: INFO: common]: created directory at: artifacts
[2024-05-27 16:52:16,619: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 16:52:16,619: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 16:53:06,946: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 16:53:07,776: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 16:53:07,777: INFO: main]: *******************
[2024-05-27 16:53:07,777: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 16:53:07,779: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 16:53:07,781: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 16:53:07,782: INFO: common]: created directory at: artifacts
[2024-05-27 16:53:07,783: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 16:53:08,386: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 16:53:08,648: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 16:53:08,649: INFO: main]: ************************************************
[2024-05-27 16:53:08,649: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 16:53:08,653: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 16:53:08,656: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 16:53:08,657: INFO: common]: created directory at: artifacts
[2024-05-27 16:53:08,658: INFO: common]: created directory at: artifacts\training
[2024-05-27 16:55:32,196: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 16:55:32,196: INFO: main]: ***********************************************
[2024-05-27 16:55:32,196: INFO: main]: >>>>>> stage Evaluation started <<<<<<<
[2024-05-27 16:55:32,198: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 16:55:32,200: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 16:55:32,201: INFO: common]: created directory at: artifacts
[2024-05-27 16:55:54,763: INFO: common]: json files saved at: scores.json
[2024-05-27 16:55:57,640: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-27 16:55:59,339: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmppdjygqso\model\data\model\assets
[2024-05-27 16:56:14,599: INFO: dir_util]: creating D:\ML projects\ML class\Kidney-Disease-Classification\mlruns\0\ed2fc405ccae4d50bde43f4abcf405e7\artifacts\model\data
[2024-05-27 16:56:14,601: INFO: dir_util]: creating D:\ML projects\ML class\Kidney-Disease-Classification\mlruns\0\ed2fc405ccae4d50bde43f4abcf405e7\artifacts\model\data\model
[2024-05-27 16:56:14,602: INFO: dir_util]: creating D:\ML projects\ML class\Kidney-Disease-Classification\mlruns\0\ed2fc405ccae4d50bde43f4abcf405e7\artifacts\model\data\model\assets
[2024-05-27 16:56:14,607: INFO: dir_util]: creating D:\ML projects\ML class\Kidney-Disease-Classification\mlruns\0\ed2fc405ccae4d50bde43f4abcf405e7\artifacts\model\data\model\variables
[2024-05-27 16:56:14,721: INFO: main]: >>>>>> stage Evaluation completed <<<<<<<

x============x
[2024-05-27 17:02:21,845: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 17:02:25,919: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 17:02:25,922: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:02:25,923: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:02:25,924: INFO: common]: created directory at: artifacts
[2024-05-27 17:02:25,925: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 17:02:25,925: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 17:02:27,248: ERROR: main]: HTTPSConnectionPool(host='doc-0s-bg-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/cbbgni03og7pqnajlfqqt0du6hba3uuh/1716800475000/13776470301398363934/*/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY?uuid=1ea4cdb7-e847-4cb3-b4f0-a95292e46c44 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C98C0D7710>: Failed to resolve 'doc-0s-bg-docs.googleusercontent.com' ([Errno 11001] getaddrinfo failed)"))
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 492, in _make_request
    raise new_e
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001C98C0D7710>: Failed to resolve 'doc-0s-bg-docs.googleusercontent.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='doc-0s-bg-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/cbbgni03og7pqnajlfqqt0du6hba3uuh/1716800475000/13776470301398363934/*/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY?uuid=1ea4cdb7-e847-4cb3-b4f0-a95292e46c44 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C98C0D7710>: Failed to resolve 'doc-0s-bg-docs.googleusercontent.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ML projects\ML class\Kidney-Disease-Classification\main.py", line 11, in <module>
    data_ingestion.main()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix + file_id, zip_download_dir)
  File "C:\Users\User\anaconda3\Lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
           ^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='doc-0s-bg-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/cbbgni03og7pqnajlfqqt0du6hba3uuh/1716800475000/13776470301398363934/*/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY?uuid=1ea4cdb7-e847-4cb3-b4f0-a95292e46c44 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C98C0D7710>: Failed to resolve 'doc-0s-bg-docs.googleusercontent.com' ([Errno 11001] getaddrinfo failed)"))
[2024-05-27 17:03:02,849: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 17:03:05,479: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 17:03:05,482: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:03:05,483: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:03:05,484: INFO: common]: created directory at: artifacts
[2024-05-27 17:03:05,485: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 17:03:05,485: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 17:03:56,206: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 17:03:57,141: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 17:03:57,142: INFO: main]: *******************
[2024-05-27 17:03:57,142: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 17:03:57,144: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:03:57,145: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:03:57,146: INFO: common]: created directory at: artifacts
[2024-05-27 17:03:57,147: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 17:03:58,179: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 17:03:58,457: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 17:03:58,457: INFO: main]: ************************************************
[2024-05-27 17:03:58,458: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 17:03:58,460: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:03:58,461: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:03:58,462: INFO: common]: created directory at: artifacts
[2024-05-27 17:03:58,462: INFO: common]: created directory at: artifacts\training
[2024-05-27 17:06:18,570: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 17:06:18,570: INFO: main]: ***********************************************
[2024-05-27 17:06:18,571: INFO: main]: >>>>>> stage Evaluation started <<<<<<<
[2024-05-27 17:06:18,573: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:06:18,577: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:06:18,577: INFO: common]: created directory at: artifacts
[2024-05-27 17:06:41,158: INFO: common]: json files saved at: scores.json
[2024-05-27 17:06:44,075: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-27 17:06:46,054: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmpt2z1r_qa\model\data\model\assets
[2024-05-27 17:07:03,641: INFO: dir_util]: creating D:\ML projects\ML class\Kidney-Disease-Classification\mlruns\0\f9fc3b6ed1d54fee832f58efcde6d82a\artifacts\model\data
[2024-05-27 17:07:03,643: INFO: dir_util]: creating D:\ML projects\ML class\Kidney-Disease-Classification\mlruns\0\f9fc3b6ed1d54fee832f58efcde6d82a\artifacts\model\data\model
[2024-05-27 17:07:03,645: INFO: dir_util]: creating D:\ML projects\ML class\Kidney-Disease-Classification\mlruns\0\f9fc3b6ed1d54fee832f58efcde6d82a\artifacts\model\data\model\assets
[2024-05-27 17:07:03,651: INFO: dir_util]: creating D:\ML projects\ML class\Kidney-Disease-Classification\mlruns\0\f9fc3b6ed1d54fee832f58efcde6d82a\artifacts\model\data\model\variables
[2024-05-27 17:07:03,780: INFO: main]: >>>>>> stage Evaluation completed <<<<<<<

x============x
[2024-05-27 17:09:53,310: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:09:53,316: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-27 17:09:53,318: INFO: common]: created directory at: artifacts
[2024-05-27 17:10:19,451: INFO: common]: json files saved at: scores.json
[2024-05-27 17:10:22,405: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-27 17:10:23,505: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmpsrf6r8q9\model\data\model\assets
[2024-05-27 17:20:21,390: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 17:20:23,804: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 17:20:23,807: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:20:23,808: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:20:23,809: INFO: common]: created directory at: artifacts
[2024-05-27 17:20:23,810: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 17:20:23,810: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 17:21:14,106: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 17:21:14,963: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 17:21:14,964: INFO: main]: *******************
[2024-05-27 17:21:14,965: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 17:21:14,970: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:21:14,975: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:21:14,977: INFO: common]: created directory at: artifacts
[2024-05-27 17:21:14,979: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 17:21:15,560: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 17:21:15,847: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 17:21:15,848: INFO: main]: ************************************************
[2024-05-27 17:21:15,848: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 17:21:15,850: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:21:15,851: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:21:15,852: INFO: common]: created directory at: artifacts
[2024-05-27 17:21:15,853: INFO: common]: created directory at: artifacts\training
[2024-05-27 17:23:32,272: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 17:23:32,272: INFO: main]: *******************
[2024-05-27 17:23:32,272: INFO: main]: >>>>>> stage Evaluation started <<<<<<
[2024-05-27 17:23:32,275: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:23:32,276: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:23:32,277: INFO: common]: created directory at: artifacts
[2024-05-27 17:23:32,696: ERROR: main]: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion/kidney-ct-scan-image'
Traceback (most recent call last):
  File "D:\ML projects\ML class\Kidney-Disease-Classification\main.py", line 46, in <module>
    model_evaluation.main()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 17, in main
    evaluation.evaluation()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 44, in evaluation
    self._valid_generator()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 31, in _valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
                         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion/kidney-ct-scan-image'
[2024-05-27 17:26:16,478: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 17:26:19,433: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 17:26:19,439: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:26:19,440: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:26:19,441: INFO: common]: created directory at: artifacts
[2024-05-27 17:26:19,442: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 17:26:19,443: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 17:27:09,371: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 17:27:10,228: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 17:27:10,228: INFO: main]: *******************
[2024-05-27 17:27:10,229: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 17:27:10,231: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:27:10,232: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:27:10,233: INFO: common]: created directory at: artifacts
[2024-05-27 17:27:10,234: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 17:27:10,776: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 17:27:11,038: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 17:27:11,038: INFO: main]: ************************************************
[2024-05-27 17:27:11,039: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 17:27:11,041: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:27:11,042: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:27:11,043: INFO: common]: created directory at: artifacts
[2024-05-27 17:27:11,044: INFO: common]: created directory at: artifacts\training
[2024-05-27 17:29:32,556: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 17:29:32,556: INFO: main]: *******************
[2024-05-27 17:29:32,556: INFO: main]: >>>>>> stage Evaluation started <<<<<<
[2024-05-27 17:29:32,559: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:29:32,560: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:29:32,561: INFO: common]: created directory at: artifacts
[2024-05-27 17:29:56,019: INFO: common]: json files saved at: scores.json
[2024-05-27 17:29:56,020: INFO: common]: json files saved at: scores.json
[2024-05-27 17:29:56,021: INFO: main]: >>>>>> stage Evaluation completed <<<<<<

x==========x
[2024-05-27 17:40:30,774: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 17:40:36,077: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 17:40:36,080: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:40:36,083: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:40:36,084: INFO: common]: created directory at: artifacts
[2024-05-27 17:40:36,084: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 17:40:36,085: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 17:41:27,838: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 17:41:29,634: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 17:41:29,635: INFO: main]: *******************
[2024-05-27 17:41:29,636: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 17:41:29,642: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:41:29,647: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:41:29,649: INFO: common]: created directory at: artifacts
[2024-05-27 17:41:29,651: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 17:41:30,187: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 17:41:30,441: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 17:41:30,442: INFO: main]: ************************************************
[2024-05-27 17:41:30,442: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 17:41:30,445: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:41:30,448: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:41:30,449: INFO: common]: created directory at: artifacts
[2024-05-27 17:41:30,449: INFO: common]: created directory at: artifacts\training
[2024-05-27 17:43:46,979: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 17:43:46,979: INFO: main]: *******************
[2024-05-27 17:43:46,979: INFO: main]: >>>>>> stage Evaluation started <<<<<<
[2024-05-27 17:43:46,982: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:43:46,983: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:43:46,984: INFO: common]: created directory at: artifacts
[2024-05-27 17:44:08,092: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-27 17:44:08,093: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-27 17:44:34,100: INFO: common]: json files saved at: scores.json
[2024-05-27 17:44:34,101: INFO: common]: json files saved at: scores.json
[2024-05-27 17:44:34,101: INFO: main]: >>>>>> stage Evaluation completed <<<<<<

x==========x
[2024-05-27 17:46:26,333: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 17:46:31,449: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 17:46:31,451: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:46:31,453: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:46:31,454: INFO: common]: created directory at: artifacts
[2024-05-27 17:46:31,454: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 17:46:31,455: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 17:47:23,091: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 17:47:24,335: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 17:47:24,336: INFO: main]: *******************
[2024-05-27 17:47:24,336: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 17:47:24,338: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:47:24,340: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:47:24,341: INFO: common]: created directory at: artifacts
[2024-05-27 17:47:24,342: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 17:47:24,895: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 17:47:25,148: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 17:47:25,149: INFO: main]: ************************************************
[2024-05-27 17:47:25,149: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 17:47:25,151: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:47:25,153: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:47:25,154: INFO: common]: created directory at: artifacts
[2024-05-27 17:47:25,155: INFO: common]: created directory at: artifacts\training
[2024-05-27 17:48:41,064: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 17:48:41,065: INFO: main]: *******************
[2024-05-27 17:48:41,065: INFO: main]: >>>>>> stage Evaluation started <<<<<<
[2024-05-27 17:48:41,070: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:48:41,071: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 17:48:41,072: INFO: common]: created directory at: artifacts
[2024-05-27 17:48:42,855: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-27 17:48:42,856: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-27 17:49:09,125: INFO: common]: json files saved at: scores.json
[2024-05-27 17:49:09,127: INFO: common]: json files saved at: scores.json
[2024-05-27 17:49:09,127: INFO: main]: >>>>>> stage Evaluation completed <<<<<<

x==========x
[2024-05-27 17:49:56,380: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-27 17:49:56,384: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-27 17:49:56,450: WARNING: connectionpool]: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /mcmlxiv/Kidney-Disease-Classification.mlflow/api/2.0/mlflow/runs/create
[2024-05-27 17:50:02,129: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:50:02,135: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-27 17:50:02,137: INFO: common]: created directory at: artifacts
[2024-05-27 17:50:26,726: INFO: common]: json files saved at: scores.json
[2024-05-27 17:50:29,566: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-27 17:50:30,502: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmp10u8dmfy\model\data\model\assets
[2024-05-27 17:59:07,966: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-27 17:59:07,969: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-27 17:59:12,741: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 17:59:12,746: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-27 17:59:12,749: INFO: common]: created directory at: artifacts
[2024-05-27 18:02:32,051: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-27 18:02:32,062: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-27 18:02:39,215: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 18:02:39,220: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-27 18:02:39,222: INFO: common]: created directory at: artifacts
[2024-05-27 18:03:02,965: INFO: common]: json files saved at: scores.json
[2024-05-27 18:19:13,001: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 18:19:16,366: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 18:19:16,369: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 18:19:16,371: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 18:19:16,371: INFO: common]: created directory at: artifacts
[2024-05-27 18:19:16,372: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 18:19:16,372: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 18:20:08,489: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 18:20:09,611: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 18:20:09,612: INFO: main]: *******************
[2024-05-27 18:20:09,613: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 18:20:09,618: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 18:20:09,623: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 18:20:09,624: INFO: common]: created directory at: artifacts
[2024-05-27 18:20:09,626: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 18:20:10,170: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 18:20:10,458: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 18:20:10,458: INFO: main]: ************************************************
[2024-05-27 18:20:10,459: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 18:20:10,461: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 18:20:10,463: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 18:20:10,463: INFO: common]: created directory at: artifacts
[2024-05-27 18:20:10,464: INFO: common]: created directory at: artifacts\training
[2024-05-27 18:21:18,516: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 18:21:18,517: INFO: main]: *******************
[2024-05-27 18:21:18,517: INFO: main]: >>>>>> stage Evaluation started <<<<<<
[2024-05-27 18:21:18,519: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 18:21:18,521: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 18:21:18,521: INFO: common]: created directory at: artifacts
[2024-05-27 18:21:41,113: INFO: common]: json files saved at: scores.json
[2024-05-27 18:21:41,115: INFO: common]: json files saved at: scores.json
[2024-05-27 18:21:42,752: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-27 18:21:42,754: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-27 18:21:46,712: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-27 18:21:48,637: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmph4rmuq27\model\data\model\assets
[2024-05-27 18:24:57,644: INFO: main]: >>>>>> stage Evaluation completed <<<<<<

x==========x
[2024-05-27 18:35:39,907: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 18:35:44,399: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 18:35:44,405: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 18:35:44,408: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 18:35:44,409: INFO: common]: created directory at: artifacts
[2024-05-27 18:35:44,410: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 18:35:44,411: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 18:36:38,706: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 18:36:39,645: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 18:36:39,646: INFO: main]: *******************
[2024-05-27 18:36:39,646: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 18:36:39,649: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 18:36:39,652: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 18:36:39,653: INFO: common]: created directory at: artifacts
[2024-05-27 18:36:39,654: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 18:36:40,347: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 18:36:40,710: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 18:36:40,711: INFO: main]: ************************************************
[2024-05-27 18:36:40,711: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 18:36:40,714: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 18:36:40,718: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 18:36:40,719: INFO: common]: created directory at: artifacts
[2024-05-27 18:36:40,719: INFO: common]: created directory at: artifacts\training
[2024-05-27 18:39:33,560: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 18:39:33,561: INFO: main]: *******************
[2024-05-27 18:39:33,562: INFO: main]: >>>>>> stage Evaluation started <<<<<<
[2024-05-27 18:39:33,567: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 18:39:33,571: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 18:39:33,573: INFO: common]: created directory at: artifacts
[2024-05-27 18:40:03,359: INFO: common]: json files saved at: scores.json
[2024-05-27 18:40:03,360: INFO: common]: json files saved at: scores.json
[2024-05-27 18:40:05,329: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-27 18:40:05,331: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-27 18:40:11,077: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-27 18:40:13,432: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmpfw3jznuj\model\data\model\assets
[2024-05-27 18:43:29,410: INFO: main]: >>>>>> stage Evaluation completed <<<<<<

x==========x
[2024-05-27 18:57:59,448: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 18:58:00,414: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 18:58:00,418: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 18:58:00,420: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 18:58:00,421: INFO: common]: created directory at: artifacts
[2024-05-27 18:58:00,422: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 18:58:00,422: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 18:58:52,550: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 18:58:53,441: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 18:58:53,442: INFO: main]: *******************
[2024-05-27 18:58:53,442: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 18:58:53,444: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 18:58:53,445: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 18:58:53,446: INFO: common]: created directory at: artifacts
[2024-05-27 18:58:53,447: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 18:58:53,990: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 18:58:54,289: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 18:58:54,289: INFO: main]: ************************************************
[2024-05-27 18:58:54,289: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 18:58:54,294: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 18:58:54,297: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 18:58:54,298: INFO: common]: created directory at: artifacts
[2024-05-27 18:58:54,299: INFO: common]: created directory at: artifacts\training
[2024-05-27 19:02:39,420: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 19:12:07,200: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 19:12:10,530: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 19:12:10,532: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 19:12:10,533: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 19:12:10,534: INFO: common]: created directory at: artifacts
[2024-05-27 19:12:10,535: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 19:12:10,535: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 19:13:09,268: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 19:13:10,014: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 19:13:10,014: INFO: main]: *******************
[2024-05-27 19:13:10,015: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 19:13:10,016: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 19:13:10,018: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 19:13:10,019: INFO: common]: created directory at: artifacts
[2024-05-27 19:13:10,019: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 19:13:10,611: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 19:13:10,979: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 19:13:10,980: INFO: main]: ************************************************
[2024-05-27 19:13:10,980: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 19:13:10,982: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 19:13:10,984: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 19:13:10,984: INFO: common]: created directory at: artifacts
[2024-05-27 19:13:10,985: INFO: common]: created directory at: artifacts\training
[2024-05-27 19:16:52,067: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 19:16:52,067: INFO: main]: *******************
[2024-05-27 19:16:52,068: INFO: main]: >>>>>> stage Evaluation started <<<<<<
[2024-05-27 19:16:52,070: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 19:16:52,072: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 19:16:52,073: INFO: common]: created directory at: artifacts
[2024-05-27 19:17:14,695: INFO: common]: json files saved at: scores.json
[2024-05-27 19:17:14,696: INFO: common]: json files saved at: scores.json
[2024-05-27 19:17:16,344: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-27 19:17:16,346: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-27 19:17:20,400: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-27 19:17:22,178: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmpvu_74u2w\model\data\model\assets
[2024-05-27 19:20:30,068: ERROR: main]: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: ''
Traceback (most recent call last):
  File "D:\ML projects\ML class\Kidney-Disease-Classification\main.py", line 45, in <module>
    model_evaluation.main()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 19, in main
    evaluation.log_into_mlflow()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 70, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\User\anaconda3\Lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
           ^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\mlflow\models\model.py", line 562, in log
    mlflow.register_model(
  File "C:\Users\User\anaconda3\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 77, in register_model
    raise e
  File "C:\Users\User\anaconda3\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 68, in register_model
    create_model_response = client.create_registered_model(name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\mlflow\tracking\client.py", line 1743, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\mlflow\tracking\_model_registry\client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\mlflow\store\model_registry\rest_store.py", line 75, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 42, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: ''
[2024-05-27 19:21:07,082: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 19:21:10,235: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 19:21:10,237: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 19:21:10,239: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 19:21:10,239: INFO: common]: created directory at: artifacts
[2024-05-27 19:21:10,240: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 19:21:10,240: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 19:22:14,595: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 19:22:15,418: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 19:22:15,419: INFO: main]: *******************
[2024-05-27 19:22:15,419: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 19:22:15,422: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 19:22:15,425: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 19:22:15,426: INFO: common]: created directory at: artifacts
[2024-05-27 19:22:15,426: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 19:22:15,970: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 19:22:16,211: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 19:22:16,212: INFO: main]: ************************************************
[2024-05-27 19:22:16,212: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 19:22:16,214: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 19:22:16,216: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 19:22:16,217: INFO: common]: created directory at: artifacts
[2024-05-27 19:22:16,218: INFO: common]: created directory at: artifacts\training
[2024-05-27 19:25:42,295: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 19:25:42,295: INFO: main]: *******************
[2024-05-27 19:25:42,296: INFO: main]: >>>>>> stage Evaluation started <<<<<<
[2024-05-27 19:25:42,298: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 19:25:42,299: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 19:25:42,300: INFO: common]: created directory at: artifacts
[2024-05-27 19:26:05,006: INFO: common]: json files saved at: scores.json
[2024-05-27 19:26:05,007: INFO: common]: json files saved at: scores.json
[2024-05-27 19:26:07,939: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-27 19:26:07,941: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-27 19:26:12,105: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-27 19:26:13,911: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmpagh90svd\model\data\model\assets
[2024-05-27 19:29:22,464: INFO: main]: >>>>>> stage Evaluation completed <<<<<<

x==========x
[2024-05-27 20:50:28,632: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 20:50:28,636: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 20:50:28,645: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 20:50:28,645: INFO: common]: created directory at: artifacts
[2024-05-27 20:50:28,646: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 20:50:28,647: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 20:50:29,329: ERROR: main]: HTTPSConnectionPool(host='doc-0s-bg-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ksect9kk5jgbamaumv1g5qibuje5ml49/1716814200000/13776470301398363934/*/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY?uuid=c171847a-6a8f-4cd9-9518-45cd32165098 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F5419DCCA0>: Failed to resolve 'doc-0s-bg-docs.googleusercontent.com' ([Errno 11001] getaddrinfo failed)"))
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\User\anaconda3\envs\myenv\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001F5419DCCA0>: Failed to resolve 'doc-0s-bg-docs.googleusercontent.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\requests\adapters.py", line 589, in send
    resp = conn.urlopen(
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='doc-0s-bg-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ksect9kk5jgbamaumv1g5qibuje5ml49/1716814200000/13776470301398363934/*/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY?uuid=c171847a-6a8f-4cd9-9518-45cd32165098 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F5419DCCA0>: Failed to resolve 'doc-0s-bg-docs.googleusercontent.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ML projects\ML class\Kidney-Disease-Classification\main.py", line 11, in <module>
    data_ingestion.main()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix + file_id, zip_download_dir)
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\requests\sessions.py", line 724, in send
    history = [resp for resp in gen]
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\requests\sessions.py", line 724, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\requests\sessions.py", line 265, in resolve_redirects
    resp = self.send(
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\User\anaconda3\envs\myenv\lib\site-packages\requests\adapters.py", line 622, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='doc-0s-bg-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ksect9kk5jgbamaumv1g5qibuje5ml49/1716814200000/13776470301398363934/*/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY?uuid=c171847a-6a8f-4cd9-9518-45cd32165098 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F5419DCCA0>: Failed to resolve 'doc-0s-bg-docs.googleusercontent.com' ([Errno 11001] getaddrinfo failed)"))
[2024-05-27 20:51:04,504: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 20:51:04,507: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 20:51:04,508: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 20:51:04,509: INFO: common]: created directory at: artifacts
[2024-05-27 20:51:04,510: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 20:51:04,510: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 20:51:52,731: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 20:51:53,869: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-27 20:51:53,869: INFO: main]: *******************
[2024-05-27 20:51:53,870: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-27 20:51:53,872: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 20:51:53,874: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 20:51:53,874: INFO: common]: created directory at: artifacts
[2024-05-27 20:51:53,875: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-27 20:51:54,542: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-27 20:51:54,809: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-27 20:51:54,809: INFO: main]: ************************************************
[2024-05-27 20:51:54,809: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-27 20:51:54,812: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 20:51:54,814: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 20:51:54,815: INFO: common]: created directory at: artifacts
[2024-05-27 20:51:54,815: INFO: common]: created directory at: artifacts\training
[2024-05-27 20:55:20,728: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-27 20:55:20,728: INFO: main]: *******************
[2024-05-27 20:55:20,728: INFO: main]: >>>>>> stage Evaluation started <<<<<<
[2024-05-27 20:55:20,731: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 20:55:20,733: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 20:55:20,734: INFO: common]: created directory at: artifacts
[2024-05-27 20:55:42,737: INFO: common]: json files saved at: scores.json
[2024-05-27 20:55:42,738: INFO: common]: json files saved at: scores.json
[2024-05-27 20:55:42,738: ERROR: main]: module 'dagshub' has no attribute 'init'
Traceback (most recent call last):
  File "D:\ML projects\ML class\Kidney-Disease-Classification\main.py", line 45, in <module>
    model_evaluation.main()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 19, in main
    evaluation.log_into_mlflow()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 54, in log_into_mlflow
    dagshub.init(repo_owner='mcmlxiv', repo_name='Kidney-Disease-Classification', mlflow=True)
AttributeError: module 'dagshub' has no attribute 'init'
[2024-05-27 21:21:26,718: INFO: utils]: NumExpr defaulting to 8 threads.
[2024-05-27 21:21:30,469: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 21:21:30,474: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 21:21:30,478: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 21:21:30,478: INFO: common]: created directory at: artifacts
[2024-05-27 21:21:30,479: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 21:21:30,480: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 22:02:01,643: INFO: data_ingestion]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 22:02:01,649: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 22:02:01,654: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 22:02:01,654: INFO: common]: created directory at: artifacts
[2024-05-27 22:02:01,655: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 22:02:01,656: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-27 22:05:11,050: INFO: data_ingestion]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-27 22:05:11,052: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-27 22:05:11,054: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-27 22:05:11,055: INFO: common]: created directory at: artifacts
[2024-05-27 22:05:11,056: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-27 22:05:11,057: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-28 14:01:41,924: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-28 14:01:41,926: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 14:01:41,928: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 14:01:41,929: INFO: common]: created directory at: artifacts
[2024-05-28 14:01:41,929: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-28 14:01:41,930: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-28 14:03:26,668: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-28 14:03:27,630: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-28 14:03:27,630: INFO: main]: *******************
[2024-05-28 14:03:27,630: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-28 14:03:27,633: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 14:03:27,635: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 14:03:27,635: INFO: common]: created directory at: artifacts
[2024-05-28 14:03:27,636: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-28 14:03:28,459: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-28 14:03:28,698: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-28 14:03:28,699: INFO: main]: ************************************************
[2024-05-28 14:03:28,699: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-28 14:03:28,702: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 14:03:28,703: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 14:03:28,704: INFO: common]: created directory at: artifacts
[2024-05-28 14:03:28,705: INFO: common]: created directory at: artifacts\training
[2024-05-28 14:06:57,112: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-28 14:06:57,112: INFO: main]: *******************
[2024-05-28 14:06:57,112: INFO: main]: >>>>>> stage Evaluation started <<<<<<
[2024-05-28 14:06:57,116: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 14:06:57,118: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 14:06:57,119: INFO: common]: created directory at: artifacts
[2024-05-28 14:07:19,269: INFO: common]: json files saved at: scores.json
[2024-05-28 14:07:19,270: INFO: common]: json files saved at: scores.json
[2024-05-28 14:07:19,270: ERROR: main]: module 'dagshub' has no attribute 'init'
Traceback (most recent call last):
  File "D:\ML projects\ML class\Kidney-Disease-Classification\main.py", line 45, in <module>
    model_evaluation.main()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 19, in main
    evaluation.log_into_mlflow()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 54, in log_into_mlflow
    dagshub.init(repo_owner='mcmlxiv', repo_name='Kidney-Disease-Classification', mlflow=True)
AttributeError: module 'dagshub' has no attribute 'init'
[2024-05-28 14:12:27,207: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2024-05-28 14:12:27,209: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 14:12:27,212: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 14:12:27,212: INFO: common]: created directory at: artifacts
[2024-05-28 14:12:27,213: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-28 14:12:27,213: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-28 14:13:16,107: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-28 14:13:17,012: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2024-05-28 14:13:17,012: INFO: main]: *******************
[2024-05-28 14:13:17,013: INFO: main]: >>>>>> stage Prepare base model started <<<<<<
[2024-05-28 14:13:17,015: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 14:13:17,017: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 14:13:17,018: INFO: common]: created directory at: artifacts
[2024-05-28 14:13:17,018: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-28 14:13:17,593: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-28 14:13:18,268: INFO: main]: >>>>>> stage Prepare base model completed <<<<<<

x==========x
[2024-05-28 14:13:18,268: INFO: main]: ************************************************
[2024-05-28 14:13:18,269: INFO: main]: >>>>>> stage Training started <<<<<<<
[2024-05-28 14:13:18,271: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 14:13:18,273: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 14:13:18,274: INFO: common]: created directory at: artifacts
[2024-05-28 14:13:18,274: INFO: common]: created directory at: artifacts\training
[2024-05-28 14:17:14,717: INFO: main]: >>>>>> stage Training completed  <<<<<<<

x============x
[2024-05-28 14:17:14,717: INFO: main]: *******************
[2024-05-28 14:17:14,718: INFO: main]: >>>>>> stage Evaluation started <<<<<<
[2024-05-28 14:17:14,724: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 14:17:14,729: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 14:17:14,730: INFO: common]: created directory at: artifacts
[2024-05-28 14:17:45,180: INFO: common]: json files saved at: scores.json
[2024-05-28 14:17:45,181: INFO: common]: json files saved at: scores.json
[2024-05-28 14:17:45,181: ERROR: main]: module 'dagshub' has no attribute 'init'
Traceback (most recent call last):
  File "D:\ML projects\ML class\Kidney-Disease-Classification\main.py", line 45, in <module>
    model_evaluation.main()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 19, in main
    evaluation.log_into_mlflow()
  File "D:\ML projects\ML class\Kidney-Disease-Classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 54, in log_into_mlflow
    dagshub.init(repo_owner='mcmlxiv', repo_name='Kidney-Disease-Classification', mlflow=True)
AttributeError: module 'dagshub' has no attribute 'init'
[2024-05-28 18:59:18,049: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 18:59:18,053: INFO: common]: yaml file: D:\ML projects\ML class\Kidney-Disease-Classification\params.yaml loaded successfully
[2024-05-28 18:59:18,056: INFO: common]: created directory at: artifacts
[2024-05-28 18:59:44,808: INFO: common]: json files saved at: scores.json
[2024-05-28 18:59:45,203: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-28 18:59:45,208: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-28 18:59:47,821: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-28 18:59:48,781: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmpchwjq5ah\model\data\model\assets
[2024-05-28 19:44:13,176: INFO: stage_01_data_ingestion]: >>>>>> stage Data Ingestion stage started <<<<<<<
[2024-05-28 19:44:13,178: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 19:44:13,183: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 19:44:13,184: INFO: common]: created directory at: artifacts
[2024-05-28 19:44:13,184: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-28 19:44:13,185: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-28 19:45:03,543: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-28 19:45:04,843: INFO: stage_01_data_ingestion]: >>>>>> stage Data Ingestion stage completed <<<<<<<

x============x
[2024-05-28 19:46:26,151: INFO: stage_01_data_ingestion]: >>>>>> stage Data Ingestion stage started <<<<<<<
[2024-05-28 19:46:26,154: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 19:46:26,156: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 19:46:26,156: INFO: common]: created directory at: artifacts
[2024-05-28 19:46:26,157: INFO: common]: created directory at: artifacts/data_ingestion
[2024-05-28 19:46:26,157: INFO: data_ingestion]: Downloading data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-28 19:47:15,373: INFO: data_ingestion]: Download data from https://drive.google.com/file/d/1SrvZQiGilu4ZbeDO94VL4r2vFpcBRUtY/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2024-05-28 19:47:16,613: INFO: stage_01_data_ingestion]: >>>>>> stage Data Ingestion stage completed <<<<<<<

x============x
[2024-05-28 19:47:36,913: INFO: stage_02_prepare_base_model]: >>>>>> stage Prepare Base Model started <<<<<<<
[2024-05-28 19:47:36,917: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 19:47:36,920: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 19:47:36,922: INFO: common]: created directory at: artifacts
[2024-05-28 19:47:36,943: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-05-28 19:47:37,884: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-05-28 19:47:38,152: INFO: stage_02_prepare_base_model]: >>>>>> stage Prepare Base Model completed <<<<<<<

x============x
[2024-05-28 19:47:46,799: INFO: stage_03_model_training]: >>>>>> stage Training started <<<<<<<
[2024-05-28 19:47:46,801: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 19:47:46,803: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 19:47:46,804: INFO: common]: created directory at: artifacts
[2024-05-28 19:47:46,804: INFO: common]: created directory at: artifacts\training
[2024-05-28 19:51:20,324: INFO: stage_03_model_training]: >>>>>> stage Training completed <<<<<<<

x============x
[2024-05-28 19:55:38,931: INFO: stage_04_model_evaluation]: *******************
[2024-05-28 19:55:38,932: INFO: stage_04_model_evaluation]: >>>>>> stage Evaluation started <<<<<<
[2024-05-28 19:55:38,934: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-05-28 19:55:38,938: INFO: common]: yaml file: params.yaml loaded successfully
[2024-05-28 19:55:38,938: INFO: common]: created directory at: artifacts
[2024-05-28 19:56:07,525: INFO: common]: json files saved at: scores.json
[2024-05-28 19:56:07,527: INFO: common]: json files saved at: scores.json
[2024-05-28 19:56:09,541: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-05-28 19:56:09,544: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-05-28 19:56:13,831: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-05-28 19:56:15,135: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmpcungp95j\model\data\model\assets
[2024-05-28 19:59:23,104: INFO: stage_04_model_evaluation]: >>>>>> stage Evaluation completed <<<<<<

x==========x
[2024-05-29 23:42:33,517: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080
[2024-05-29 23:42:33,538: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2024-05-29 23:42:47,016: INFO: _internal]: 127.0.0.1 - - [29/May/2024 23:42:47] "GET / HTTP/1.1" 200 -
[2024-05-29 23:44:14,085: INFO: _internal]: 127.0.0.1 - - [29/May/2024 23:44:14] "POST /predict HTTP/1.1" 200 -
[2024-05-29 23:44:31,244: INFO: _internal]: 127.0.0.1 - - [29/May/2024 23:44:31] "POST /predict HTTP/1.1" 200 -
[2024-05-29 23:44:43,479: INFO: _internal]: 127.0.0.1 - - [29/May/2024 23:44:43] "POST /predict HTTP/1.1" 200 -
[2024-05-29 23:44:58,300: INFO: _internal]: 127.0.0.1 - - [29/May/2024 23:44:58] "POST /predict HTTP/1.1" 200 -
[2024-05-29 23:46:10,220: WARNING: polymorphic_function]: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000023952280E50> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[2024-05-29 23:46:10,225: INFO: _internal]: 127.0.0.1 - - [29/May/2024 23:46:10] "POST /predict HTTP/1.1" 200 -
[2024-06-01 20:20:28,736:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:20:28,848:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:20:28,924:INFO:common:created directory at: artifacts]
[2024-06-01 20:20:28,937:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:21:19,835:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:21:19,839:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:21:19,842:INFO:common:created directory at: artifacts]
[2024-06-01 20:21:19,844:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:21:19,846:INFO:175609919:Downloading data from https://drive.google.com/file/d/1Dv281FPttZuUNdjpatpCpY70N8yqi6Mq/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-01 20:30:47,527:INFO:175609919:Download data from https://drive.google.com/file/d/1Dv281FPttZuUNdjpatpCpY70N8yqi6Mq/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-01 20:35:42,569:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:35:42,574:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:35:42,576:INFO:common:created directory at: artifacts]
[2024-06-01 20:35:42,578:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:36:03,029:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:36:03,033:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:36:03,036:INFO:common:created directory at: artifacts]
[2024-06-01 20:36:03,039:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:40:56,833:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:40:56,837:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:40:56,839:INFO:common:created directory at: artifacts]
[2024-06-01 20:40:56,841:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:42:31,467:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:42:31,472:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:42:31,474:INFO:common:created directory at: artifacts]
[2024-06-01 20:42:31,477:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:43:16,144:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:43:16,149:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:43:16,152:INFO:common:created directory at: artifacts]
[2024-06-01 20:43:16,154:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:44:14,862:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:44:14,866:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:44:14,868:INFO:common:created directory at: artifacts]
[2024-06-01 20:44:14,870:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:51:18,729:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:51:18,733:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:51:18,735:INFO:common:created directory at: artifacts]
[2024-06-01 20:51:18,738:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:53:57,190:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:53:57,194:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:53:57,196:INFO:common:created directory at: artifacts]
[2024-06-01 20:53:57,198:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:54:18,017:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:54:18,021:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:54:18,024:INFO:common:created directory at: artifacts]
[2024-06-01 20:54:18,025:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:54:50,534:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:54:50,539:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:54:50,541:INFO:common:created directory at: artifacts]
[2024-06-01 20:54:50,543:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:56:10,601:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:56:10,606:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:56:10,608:INFO:common:created directory at: artifacts]
[2024-06-01 20:56:10,611:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:57:05,621:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:57:05,625:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:57:05,627:INFO:common:created directory at: artifacts]
[2024-06-01 20:57:05,629:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:57:25,262:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:57:25,266:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:57:25,268:INFO:common:created directory at: artifacts]
[2024-06-01 20:57:25,270:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 20:58:40,965:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 20:58:40,970:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 20:58:40,972:INFO:common:created directory at: artifacts]
[2024-06-01 20:58:40,974:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:02:20,462:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 21:02:20,597:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 21:02:20,689:INFO:common:created directory at: artifacts]
[2024-06-01 21:02:20,692:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:03:34,496:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 21:03:34,500:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 21:03:34,503:INFO:common:created directory at: artifacts]
[2024-06-01 21:03:34,505:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:12:37,340:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 21:12:37,346:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 21:12:37,349:INFO:common:created directory at: artifacts]
[2024-06-01 21:12:37,351:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:13:10,865:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 21:13:10,869:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 21:13:10,872:INFO:common:created directory at: artifacts]
[2024-06-01 21:13:10,874:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:13:48,663:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 21:13:48,667:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 21:13:48,669:INFO:common:created directory at: artifacts]
[2024-06-01 21:13:48,670:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:16:00,730:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 21:16:00,734:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 21:16:00,737:INFO:common:created directory at: artifacts]
[2024-06-01 21:16:00,739:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:18:54,049:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 21:18:54,108:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 21:18:54,129:INFO:common:created directory at: artifacts]
[2024-06-01 21:18:54,132:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:24:17,729:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 21:24:17,734:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 21:24:17,736:INFO:common:created directory at: artifacts]
[2024-06-01 21:24:17,738:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:28:00,880:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 21:28:00,968:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 21:28:00,994:INFO:common:created directory at: artifacts]
[2024-06-01 21:28:00,996:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:32:39,161:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 21:32:39,254:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 21:32:39,270:INFO:common:created directory at: artifacts]
[2024-06-01 21:32:39,273:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:36:52,869:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 21:36:52,873:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 21:36:52,876:INFO:common:created directory at: artifacts]
[2024-06-01 21:36:52,878:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:43:39,342:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-06-01 21:43:39,346:INFO:common:yaml file: params.yaml loaded successfully]
[2024-06-01 21:43:39,349:INFO:common:created directory at: artifacts]
[2024-06-01 21:43:39,351:INFO:common:created directory at: artifacts/data_ingestion]
[2024-06-01 21:45:37,648: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-01 21:45:37,652: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-01 21:45:37,654: INFO: common]: created directory at: artifacts
[2024-06-01 21:53:49,455: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-01 21:53:49,460: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-01 21:53:49,462: INFO: common]: created directory at: artifacts
[2024-06-01 21:53:49,465: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-06-01 21:56:07,196: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-01 21:56:07,201: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-01 21:56:07,203: INFO: common]: created directory at: artifacts
[2024-06-01 21:56:07,205: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-06-01 21:57:15,032: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-01 21:57:15,037: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-01 21:57:15,039: INFO: common]: created directory at: artifacts
[2024-06-01 21:57:15,041: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-06-01 22:04:57,484: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-01 22:04:57,559: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-01 22:04:57,584: INFO: common]: created directory at: artifacts
[2024-06-01 22:04:57,586: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-06-01 22:07:25,033: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-01 22:07:25,036: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-01 22:07:25,039: INFO: common]: created directory at: artifacts
[2024-06-01 22:07:25,041: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-06-01 22:13:58,143: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-01 22:13:58,148: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-01 22:13:58,150: INFO: common]: created directory at: artifacts
[2024-06-01 22:13:58,152: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-06-01 23:02:08,146: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-01 23:02:08,360: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-01 23:02:08,483: INFO: common]: created directory at: artifacts
[2024-06-01 23:02:28,970: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-01 23:02:28,975: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-01 23:02:28,978: INFO: common]: created directory at: artifacts
[2024-06-01 23:02:29,027: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-06-01 23:06:21,155: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-06-01 23:21:16,293: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-01 23:21:16,298: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-01 23:21:16,300: INFO: common]: created directory at: artifacts
[2024-06-01 23:21:16,302: INFO: common]: created directory at: artifacts\training
[2024-06-01 23:24:02,006: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-01 23:24:02,010: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-01 23:24:02,013: INFO: common]: created directory at: artifacts
[2024-06-01 23:24:02,016: INFO: common]: created directory at: artifacts\training
[2024-06-01 23:36:55,056: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-01 23:36:55,060: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-01 23:36:55,062: INFO: common]: created directory at: artifacts
[2024-06-01 23:36:55,064: INFO: common]: created directory at: artifacts\training
[2024-06-02 00:08:35,728: INFO: stage_02_prepare_base_model]: >>>>>> stage Prepare Base Model started <<<<<<<
[2024-06-02 00:08:35,731: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-02 00:08:35,733: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-02 00:08:35,734: INFO: common]: created directory at: artifacts
[2024-06-02 00:08:35,734: INFO: common]: created directory at: artifacts/prepare_base_model
[2024-06-02 00:08:36,625: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-06-02 00:08:36,876: INFO: stage_02_prepare_base_model]: >>>>>> stage Prepare Base Model completed <<<<<<<

x============x
[2024-06-02 00:08:45,586: INFO: stage_03_model_training]: >>>>>> stage Training started <<<<<<<
[2024-06-02 00:08:45,589: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-02 00:08:45,591: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-02 00:08:45,592: INFO: common]: created directory at: artifacts
[2024-06-02 00:08:45,593: INFO: common]: created directory at: artifacts\training
[2024-06-02 00:44:28,296: INFO: stage_03_model_training]: >>>>>> stage Training completed <<<<<<<

x============x
[2024-06-02 00:44:41,901: INFO: stage_04_model_evaluation]: *******************
[2024-06-02 00:44:41,901: INFO: stage_04_model_evaluation]: >>>>>> stage Evaluation started <<<<<<
[2024-06-02 00:44:41,904: INFO: common]: yaml file: config\config.yaml loaded successfully
[2024-06-02 00:44:41,907: INFO: common]: yaml file: params.yaml loaded successfully
[2024-06-02 00:44:41,907: INFO: common]: created directory at: artifacts
[2024-06-02 00:45:08,197: INFO: common]: json files saved at: scores.json
[2024-06-02 00:45:08,198: INFO: common]: json files saved at: scores.json
[2024-06-02 00:45:09,127: INFO: _client]: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[2024-06-02 00:45:10,113: INFO: _client]: HTTP Request: GET https://dagshub.com/api/v1/repos/mcmlxiv/Kidney-Disease-Classification "HTTP/1.1 200 OK"
[2024-06-02 00:45:10,131: INFO: helpers]: Initialized MLflow to track repo "mcmlxiv/Kidney-Disease-Classification"
[2024-06-02 00:45:10,134: INFO: helpers]: Repository mcmlxiv/Kidney-Disease-Classification initialized!
[2024-06-02 00:45:13,840: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-06-02 00:45:16,095: INFO: builder_impl]: Assets written to: C:\Users\User\AppData\Local\Temp\tmp8_gun2g3\model\data\model\assets
[2024-06-02 00:48:53,103: INFO: stage_04_model_evaluation]: >>>>>> stage Evaluation completed <<<<<<

x==========x
[2024-06-02 20:54:49,197: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080
[2024-06-02 20:54:49,198: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2024-06-02 20:54:53,582: INFO: _internal]: 127.0.0.1 - - [02/Jun/2024 20:54:53] "GET / HTTP/1.1" 200 -
[2024-06-02 20:54:54,884: INFO: _internal]: 127.0.0.1 - - [02/Jun/2024 20:54:54] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2024-06-02 20:59:23,784: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080
[2024-06-02 20:59:23,785: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2024-06-02 20:59:29,422: INFO: _internal]: 127.0.0.1 - - [02/Jun/2024 20:59:29] "GET / HTTP/1.1" 200 -
[2024-06-02 21:00:56,406: INFO: _internal]: 127.0.0.1 - - [02/Jun/2024 21:00:56] "GET / HTTP/1.1" 200 -
